In [ ]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
df = pd.read_csv("../data/alzheimers_disease_data.csv")
df.head()

,PatientID,Age,Gender,Ethnicity,EducationLevel,BMI,Smoking,AlcoholConsumption,PhysicalActivity,DietQuality,...,MemoryComplaints,BehavioralProblems,ADL,Confusion,Disorientation,PersonalityChanges,DifficultyCompletingTasks,Forgetfulness,Diagnosis,DoctorInCharge
0,4751,73,0,0,2,22.927749,0,13.297218,6.327112,1.347214,...,0,0,1.725883,0,0,0,1,0,0,XXXConfid
1,4752,89,0,0,0,26.827681,0,4.542524,7.619885,0.518767,...,0,0,2.592424,0,0,0,0,1,0,XXXConfid
2,4753,73,0,3,1,17.795882,0,19.555085,7.844988,1.826335,...,0,0,7.119548,0,1,0,1,0,0,XXXConfid
3,4754,74,1,0,1,33.800817,1,12.209266,8.428001,7.435604,...,0,1,6.481226,0,0,0,0,0,0,XXXConfid
4,4755,89,0,0,0,20.716974,0,18.454356,6.310461,0.795498,...,0,0,0.014691,0,0,1,1,0,0,XXXConfid

In [ ]:
df = df.drop("PatientID", axis=1)
df.head()

,Age,Gender,Ethnicity,EducationLevel,BMI,Smoking,AlcoholConsumption,PhysicalActivity,DietQuality,SleepQuality,...,MemoryComplaints,BehavioralProblems,ADL,Confusion,Disorientation,PersonalityChanges,DifficultyCompletingTasks,Forgetfulness,Diagnosis,DoctorInCharge
0,73,0,0,2,22.927749,0,13.297218,6.327112,1.347214,9.025679,...,0,0,1.725883,0,0,0,1,0,0,XXXConfid
1,89,0,0,0,26.827681,0,4.542524,7.619885,0.518767,7.151293,...,0,0,2.592424,0,0,0,0,1,0,XXXConfid
2,73,0,3,1,17.795882,0,19.555085,7.844988,1.826335,9.673574,...,0,0,7.119548,0,1,0,1,0,0,XXXConfid
3,74,1,0,1,33.800817,1,12.209266,8.428001,7.435604,8.392554,...,0,1,6.481226,0,0,0,0,0,0,XXXConfid
4,89,0,0,0,20.716974,0,18.454356,6.310461,0.795498,5.597238,...,0,0,0.014691,0,0,1,1,0,0,XXXConfid

In [ ]:
df = df.drop("DoctorInCharge", axis=1)
df.head()

,Age,Gender,Ethnicity,EducationLevel,BMI,Smoking,AlcoholConsumption,PhysicalActivity,DietQuality,SleepQuality,...,FunctionalAssessment,MemoryComplaints,BehavioralProblems,ADL,Confusion,Disorientation,PersonalityChanges,DifficultyCompletingTasks,Forgetfulness,Diagnosis
0,73,0,0,2,22.927749,0,13.297218,6.327112,1.347214,9.025679,...,6.518877,0,0,1.725883,0,0,0,1,0,0
1,89,0,0,0,26.827681,0,4.542524,7.619885,0.518767,7.151293,...,7.118696,0,0,2.592424,0,0,0,0,1,0
2,73,0,3,1,17.795882,0,19.555085,7.844988,1.826335,9.673574,...,5.895077,0,0,7.119548,0,1,0,1,0,0
3,74,1,0,1,33.800817,1,12.209266,8.428001,7.435604,8.392554,...,8.965106,0,1,6.481226,0,0,0,0,0,0
4,89,0,0,0,20.716974,0,18.454356,6.310461,0.795498,5.597238,...,6.045039,0,0,0.014691,0,0,1,1,0,0

In [ ]:
X = df.drop("Diagnosis", axis=1)
y = df["Diagnosis"]
print("Feature Shape:", X.shape)
print("Target Shape:", y.shape)

Feature Shape: (2149, 32)
Target Shape: (2149,)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training Features:", X_train.shape)
print("Testing Features:", X_test.shape)
print("Training Labels:", y_train.shape)
print("Testing Labels:", y_test.shape)

Training Features: (1719, 32)
Testing Features: (430, 32)
Training Labels: (1719,)
Testing Labels: (430,)

In [ ]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
print("Training Data Shape", X_train_scaled.shape)
print("Testing Data Shape", X_test_scaled.shape)

Training Data Shape (1719, 32)
Testing Data Shape (430, 32)

In [ ]:
X_train_scaled[:5]

array([[ 1.32852308,  0.99941844,  1.30905803, -0.31336327,  0.01065932,
         1.57696399,  1.13666856, -1.64897284,  0.32795912,  0.45404862,
        -0.57667854, -0.39891965, -0.42881732, -0.51197123, -0.33236293,
        -0.42405371,  1.18738838,  0.82003274, -1.69123942, -0.98513025,
        -0.97510938, -0.71046627,  1.23439164, -0.68665172, -0.509255  ,
        -0.43071712,  0.56772702, -0.50199892, -0.4345074 , -0.41734917,
        -0.43922839, -0.64948921],
       [-0.54736743, -1.0005819 , -0.70190779,  1.89883988,  1.30582655,
        -0.63412989, -1.49210597,  1.5215992 , -1.0872222 , -1.03546622,
         1.73406834, -0.39891965, -0.42881732, -0.51197123, -0.33236293,
        -0.42405371,  0.37588643,  0.2006599 , -1.21969766,  1.3171018 ,
         0.03844378,  0.53494262, -0.74632357,  0.18934908, -0.509255  ,
         2.32170941, -0.36860359, -0.50199892, -0.4345074 , -0.41734917,
        -0.43922839,  1.53967147],
       [ 0.77679057,  0.99941844,  2.31454094,  0.7927383 , -1.63435929,
        -0.63412989,  1.09959265, -1.07068297,  0.56377158, -0.50742496,
        -0.57667854,  2.50677049,  2.33199534, -0.51197123, -0.33236293,
        -0.42405371, -1.71083288,  1.27048572,  0.22003839, -1.11212849,
         1.62989656, -0.53126421,  0.72992692, -0.48699818, -0.509255  ,
        -0.43071712, -0.32477223, -0.50199892, -0.4345074 ,  2.39607522,
         2.27671984, -0.64948921],
       [ 0.11471157,  0.99941844, -0.70190779,  0.7927383 ,  0.36283557,
         1.57696399,  0.31786666,  0.47372263,  0.42482919, -0.12112093,
        -0.57667854, -0.39891965, -0.42881732, -0.51197123, -0.33236293,
        -0.42405371, -1.51761813,  1.66463207,  0.20473547, -0.54031877,
        -1.53782416,  0.01479778,  1.60608333, -0.14588664, -0.509255  ,
        -0.43071712,  1.48806593,  1.99203617, -0.4345074 ,  2.39607522,
        -0.43922839,  1.53967147],
       [-1.54048593, -1.0005819 , -0.70190779,  0.7927383 , -0.43318581,
         1.57696399, -1.33399977,  1.78114025, -1.00518858, -1.32136922,
        -0.57667854, -0.39891965, -0.42881732, -0.51197123, -0.33236293,
        -0.42405371,  1.34196018, -1.15069903,  1.4464012 , -1.5185898 ,
         0.84229441, -0.03813288, -1.40200536,  1.56823036,  1.96365277,
        -0.43071712,  1.30590966, -0.50199892,  2.30145678, -0.41734917,
        -0.43922839, -0.64948921]])

In [ ]:
import pandas as pd 
scaled_df = pd.DataFrame(X_train_scaled, columns=X_train.columns)
print("Mean of scaled features:")
print(scaled_df.mean().head())

print("\n Standard Deviation of scaled features:")
print(scaled_df.std().head())

Mean of scaled features:
Age              -3.306772e-16
Gender           -1.343376e-17
Ethnicity        -9.816981e-18
EducationLevel    2.480079e-17
BMI               1.043700e-16
dtype: float64

 Standard Deviation of scaled features:
Age               1.000291
Gender            1.000291
Ethnicity         1.000291
EducationLevel    1.000291
BMI               1.000291
dtype: float64